image: gitpod/workspace-yugabytedb

github:
  prebuilds:
    branches: true
    master: true
    main: true

tasks:
  - name: 1a-ybdb
    env:
      HOST_LB: "127.0.0.1"
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb --advertise_address=$HOST_LB
  - name: 1b-ysqlsh
    command: |
      gp ports await 5433
      ysqlsh -f src/main/resources/init/post-create.sql
      ysqlsh
  - name: 2a-install-postgres
    init:
      sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      sudo apt -y update
      sudo apt -y install postgresql-14 postgresql-contrib-14
    command: |
      sudo su postgres -c "pg_ctlcluster 14 main start"
#      sudo su postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'postgres';\""
#      sudo su postgres -c "psql -c \"CREATE DATABASE todo;\""
  - name: 2b-psql
    command: |
      gp ports await 5432
      sudo su postgres -c "psql -f src/main/resources/init/post-create.sql"
      sudo su postgres -c "psql"
  - name: 3a-jvm-install
    init: |
      echo y | sdk install java 17.0.5-librca || true
      gp sync-done jvm-17
  - name: 3b-gradle-test
    env:
      SI: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.singleIdentityFlow\""
      SS: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.singleSequenceFlow\""
      GI: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.groupIdentityFlow\""
      GS: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.groupSequenceFlow\""
      PS: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.partitionSequenceFlow\""
      PGS: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.partitionGroupSequenceFlow\""
      SU: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.singleUUIDFlow\""
      GU: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.groupUUIDFlow\""
      NS: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.nativeSequenceFlow\""
      NU: "gradle --rerun-tasks -i --offline test --tests \"io.humourmind.todo.TodoTestRunner.nativeUUIDFlow\""
    init: |
      gp sync-await jvm-17
      gradle compileTestJava
    command: |
      bash