image: gitpod/workspace-yugabytedb

github:
  prebuilds:
    branches: true
    master: true
    main: true

tasks:
  - name: 1a-ybdb
    env:
      HOST_LB: "127.0.0.1"
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb --advertise_address=$HOST_LB
  - name: 1b-ysqlsh
    command: |
      gp ports await 5433
      ysqlsh -f src/main/resources/init/post-create.sql
      ysqlsh
  - name: 2a-install-postgres
    init: |
      sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      sudo apt -y update
      sudo apt -y install postgresql-14 postgresql-contrib-14
    command: |
      sudo su postgres -c "pg_ctlcluster 14 main start"
  - name: 2b-psql
    command: |
      gp ports await 5432
      sudo su postgres -c "psql -f src/main/resources/init/post-create.sql"
      sudo su postgres -c "psql"
  - name: 3a-jvm-install
    init: |
      echo y | sdk install java 17.0.5-librca || true
      gp sync-done jvm-17
  - name: 3b-gradle-test
    env:
      SI: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.singleIdentityFlow")
      SS: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.singleSequenceFlow")
      GI: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.groupIdentityFlow")
      GS: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.groupSequenceFlow")
      PS: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.partitionSequenceFlow")
      PGS: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.partitionGroupSequenceFlow")
      SU: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.singleUUIDFlow")
      GU: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.groupUUIDFlow")
      NS: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.nativeSequenceFlow")
      NU: (gradle -PrunTest --rerun-tasks -i test --tests "io.humourmind.todo.TodoRunnerTest.nativeUUIDFlow")
    init: |
      gp sync-await jvm-17
      gradle test
    command: |
      bash