management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
#    baseline-on-migrate: true
#    mixed: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: true
#        jdbc:
#          batch_size: 50
#        show_sql: true
#        format_sql: true
#        query:
#          substitutions: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/todo
    username: postgres
    password: postgres

springdoc:
  api-docs:
    path: "/openapi"
    resolve-schema-properties: true
  swagger-ui:
    path: "/swagger"

location:
  key:
  trigger: false
