spring:
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
  datasource:
    url: jdbc:postgresql://127.0.0.2:5433/todo
#    url: jdbc:postgresql://127.0.0.2:5433/todo?reWriteBatchedInserts=true
    username: yugabyte
    password: yugabyte