-- DROP TABLE IF EXISTS todo;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS todo
(
    id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    task         text,
    status       boolean,
    created_at   timestamp default now()
);

CREATE SEQUENCE IF NOT EXISTS todo_s_id_seq START 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS todo_s
(
    id           integer DEFAULT nextval('todo_s_id_seq') PRIMARY KEY,
    task         text,
    status       boolean,
    created_at   timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS todo_i
(
--     id           serial PRIMARY KEY,
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task         text,
    status       boolean,
    created_at   timestamp NOT NULL default now()
);

-- partitioned table flow

CREATE TABLE todo_ip
(
    id           serial,
    created_at   timestamp NOT NULL DEFAULT now(),
    task         text,
    status       boolean,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE todo_ip_2023 PARTITION OF todo_ip FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');

CREATE SEQUENCE IF NOT EXISTS todo_sp_id_seq START 1;

CREATE TABLE todo_sp
(
    id           integer NOT NULL DEFAULT nextval('todo_sp_id_seq'),
    created_at   timestamp NOT NULL DEFAULT now(),
    task         text,
    status       boolean,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE todo_sp_2023 PARTITION OF todo_sp FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');